#!/bin/bash

# Shared FastAPI runtime config for deploy scripts.
# Environment variables can override these defaults.

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$DEPLOY_DIR/.." && pwd)"

DEPLOY_TARGET="${DEPLOY_TARGET:-generic}"
APP_HOST="${APP_HOST:-0.0.0.0}"
APP_PORT="${APP_PORT:-8000}"
APP_WORKERS="${APP_WORKERS:-8}"
APP_CONDA_ENV="${APP_CONDA_ENV:-}"
APP_PYTHON="${APP_PYTHON:-}"
APP_FALLBACK_PYTHON="${APP_FALLBACK_PYTHON:-}"
CONDA_SH="${CONDA_SH:-}"

FRONTEND_HOST="${FRONTEND_HOST:-0.0.0.0}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"
FRONTEND_DIR="${FRONTEND_DIR:-$PROJECT_ROOT/frontend-workflow}"
FRONTEND_NPM="${FRONTEND_NPM:-}"
VITE_API_BASE_URL="${VITE_API_BASE_URL:-}"

MODEL_SERVER_ENV_FILE="${MODEL_SERVER_ENV_FILE:-logs/model_servers.env}"
PAPER2ANY_ASSET_ROOT="${PAPER2ANY_ASSET_ROOT:-}"

SAM3_SERVER_URLS="${SAM3_SERVER_URLS:-http://127.0.0.1:8021}"
SAM3_HOME="${SAM3_HOME:-}"
SAM3_CHECKPOINT_PATH="${SAM3_CHECKPOINT_PATH:-}"
SAM3_BPE_PATH="${SAM3_BPE_PATH:-}"
RMBG_MODEL_PATH="${RMBG_MODEL_PATH:-}"
